
mini={
  LinearLayout;
  layout_height="40sp";
  layout_width="40sp";
  {
    ImageView;
    layout_height="45sp";
    layout_width="45sp";
    src="icon.png";
    id="mmw";

  };
};
bigger={
  LinearLayout;
  layout_width="-1";
  layout_height="-1";
  background="transparent";
  orientation="horizontal";
  {
    LinearLayout;
    layout_height="250sp";
    layout_width="50sp";
    id="bbw";
    orientation="vertical";
    gravity="right";
    {
      LinearLayout;
      layout_height="95sp";
      layout_width="50sp";
      gravity="right";
      {
        LinearLayout;
        layout_height="93sp";
        layout_width="48sp";
        backgroundColor="0x3EFFFFFF";
      };
    };
    {
      LinearLayout;
      layout_height="155sp";
      layout_width="fill";
      orientation="vertical";
      gravity="vertical";
      {
        ScrollView;
        layout_height="fill";
        layout_width="fill";
        {
          LinearLayout;
          layout_height="fill";
          layout_width="fill";
          orientation="vertical";
          gravity="vertical";
          {
            LinearLayout;
            layout_width="fill";
            layout_height="50sp";
            gravity="center";
            {
              ImageView;
              layout_height="40sp";
              layout_width="40sp";
              src="res/esp.png";
              id="menu1";
              colorFilter="0xFFA0A0A0";
            };
          };
          {
            LinearLayout;
            layout_height="50sp";
            layout_width="fill";
            gravity="center";
            {
              ImageView;
              layout_height="45sp";
              layout_width="45sp";
              src="res/player.png";
              id="menu2";
              colorFilter="0xC9BCBCBC";
            };
          };
          {
            LinearLayout;
            layout_height="50sp";
            layout_width="fill";
            gravity="center";
            {
              ImageView;
              layout_height="45sp";
              layout_width="45sp";
              src="res/weap.png";
              id="menu3";
              colorFilter="0xC9BCBCBC";
            };
          };
          {
            LinearLayout;
            layout_height="50sp";
            layout_width="fill";
            gravity="center";
            {
              ImageView;
              layout_height="45sp";
              layout_width="45sp";
              src="res/vip.png";
              id="menu4";
              colorFilter="0xC9BCBCBC";
            };
          };
          {
            LinearLayout;
            layout_height="50sp";
            layout_width="fill";
            gravity="center";
            {
              ImageView;
              layout_height="45sp";
              layout_width="45sp";
              src="res/set.png";
              id="menu5";
              colorFilter="0xBD898B8B";
            };
          };
          {
            LinearLayout;
            layout_height="50sp";
            layout_width="fill";
            gravity="center";
            {
              ImageView;
              layout_height="45sp";
              layout_width="45sp";
              src="res/exit.png";
              colorFilter="0xF3A0A0A0";
              id="exitMenu";
            };
          };
        };
      };
    };
  };
  {
    LinearLayout;
    layout_height="250sp";
    layout_width="160sp";
    backgroundColor="0x83000000";
    orientation="vertical";
    id="mmss";
    {
      LinearLayout;
      layout_height="30sp";
      layout_width="fill";
      gravity="right";
      {
        LinearLayout;
        layout_height="fill";
        layout_width="130sp";
        gravity="center";
        {
          TextView;
          text="Lumen Injector";
          textSize="18sp";
          textColor="0xFFBCBCBC";
        };
      };
      {
        LinearLayout;
        layout_height="fill";
        layout_width="30sp";
        {
          ImageView;
          layout_height="fill";
          layout_width="fill";
          src="res/hide.png";
          id="close";
          colorFilter="0xC9BCBCBC";
        };
      };
    };
    {
      PageView;
      id="pg";
      layout_width="fill";
      layout_height="fill";
      pages={
        {
          ScrollView;
          layout_width="fill";
          layout_height="fill";
          {
            LinearLayout;
            layout_height="fill";
            layout_width="fill";
            orientation="vertical";
            {
              CheckBox;
              text="INITIALIZE ESP";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="绘制";
            };
            {
              CheckBox;
              text="BOX";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="方框";
            };
            {
              CheckBox;
              text="LINE";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="射线";
            };
            {
              CheckBox;
              text="INFO";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="信息";
            };
            {
              CheckBox;
              text="360°ALERT";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="背敌";
            };
            {
              TextView;
              layout_gravity="center";
              text="CONFIG";
              textSize="12.5sp";
              textColor="0xFFCDCDCD";
            };
            {
              SeekBar;
              id="调整度";
              layout_width="match_parent";
            };
          };
        };
        {
          ScrollView;
          layout_width="fill";
          layout_height="fill";
          {
            LinearLayout;
            layout_height="fill";
            layout_width="fill";
            orientation="vertical";

            {
              LinearLayout;
              gravity="center";
              layout_width="fill";
              layout_height="wrap_content";

            };
            {
              CheckBox;
              text="ANTIDEATH";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="antideath";
            };
            {
              CheckBox;
              text="FORCED CONSTRUCTION";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="stroika";
            };

            {
              CheckBox;
              text="DELETE MAP";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="nomap";
            };
            {
              CheckBox;
              text="WHITE";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="white";
            };
            {
              CardView;
              text="Man";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="Man";
            };
            {
              CardView;
              text="Man";

              id="Man";
              layout_width="match_parent";
              layout_height="30dp";

              radius="25dp";
              backgroundColor="0xFF3D3D3D";


              {
                TextView;
                text="Man";
                textSize="15sp";
                textColor="0xFFCDCDCD";
                layout_gravity="center";
              };
            };
            {
              CardView;
              text="Woman";
              layout_padding="5dp";
              id="Woman";
              layout_width="match_parent";
              layout_height="30dp";
              radius="25dp";
              layout_marginTop="10dp";
              backgroundColor="0xFF3D3D3D";
              {
                TextView;
                text="Woman";
                textSize="15sp";
                textColor="0xFFCDCDCD";
                layout_gravity="center";
              };
            };

            {
              CheckBox;
              text="BLACK";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="black";
            };
            {
              CheckBox;
              text="NIGHT";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="night";
            };
            {
              CheckBox;
              text="WATER";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="water";
            };
            {
              CheckBox;
              text="IPAD";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="ipad";
            };
            {
              CheckBox;
              text="DAY";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="day";
            };
            {
              CheckBox;
              text="VISUAL BUILD";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="build3";
            };
            {
              CheckBox;
              text="HIDE BUILDINGS AND TREES";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="hide1";
            };
            {
              CheckBox;
              text="JUMP SPEED";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="jump_s";
            };
            {
              CheckBox;
              text="ACCELERATE ACTION";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="speed";
            };
            {
              TextView;
              text="Antenna Menu";
              textSize="20sp";
              textColor="0xFFCDCDCD";
              layout_gravity="center";
            };
            {
              CheckBox;
              text="ANTENA ORE";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="rudall";
            };
            {
              CheckBox;
              text="ANTENA";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="antena";
            };
            {
              CheckBox;
              text="ANTENA SLEEPING BAG";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="antena";
            };
            {
              CheckBox;
              text="ANTENA DEATH BOX";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="antena";
            };
          };
        };
        {
          ScrollView;
          layout_width="fill";
          layout_height="fill";
          {
            LinearLayout;
            layout_height="fill";
            layout_width="fill";
            orientation="vertical";
            {
              LinearLayout;
              layout_height="20sp";
              layout_width="fill";
              orientation="vertical";
              gravity="center";
              {
                TextView;
                text="NO RECOIL";
                textSize="15sp";
                textColor="0xFFCDCDCD";
              };
            };
            {
              CheckBox;
              text="AKM AND M762";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="akm_m762";
            };
            {
              CheckBox;
              text="M4";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="m4";
            };
            {
              CheckBox;
              text="QBZ";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="qbz";
            };
            {
              CheckBox;
              text="SHOTGUN";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="shotgun";
            };
            {
              CheckBox;
              text="SMG";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="smg";
            };
            {
              CheckBox;
              text="FAMAS";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="famas";
            };
            {
              CheckBox;
              text="UZI";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="uzi";
            };
            {
              LinearLayout;
              layout_height="20sp";
              layout_width="fill";
              orientation="vertical";
              gravity="center";
              {
                TextView;
                text="MAGIC";
                textSize="15sp";
                textColor="0xFFCDCDCD";
              };
            };
            {
              CheckBox;
              text="MAGIC 30%";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="magic1";
            };
            {
              CheckBox;
              text="MAGIC 50%";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="magic2";
            };
            {
              CheckBox;
              text="MAGIC 100%";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="magic3";
            };
            {
              LinearLayout;
              layout_height="20sp";
              layout_width="fill";
              orientation="vertical";
              gravity="center";
              {
                TextView;
                text="OTHER";
                textSize="15sp";
                textColor="0xFFCDCDCD";
              };
            };
            {
              CheckBox;
              text="SCOPE 10x";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="scopex";
            };
            {
              CheckBox;
              text="FAST RELOAD";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="reload";

            };
          };
        };
        {
          ScrollView;
          layout_width="fill";
          layout_height="fill";
          {
            LinearLayout;
            layout_height="fill";
            layout_width="fill";
            orientation="vertical";
            {
              CheckBox;
              text="BULLET TRACK HEAD";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="fpss";
            };
            {
              CheckBox;
              text="GM";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="gm";
            };
            {
              LinearLayout;
              layout_height="15dp";
              layout_width="match_parent";
              background="";
              id="";


            };
          };
        };
        {
          ScrollView;
          layout_width="fill";
          layout_height="fill";
          {
            LinearLayout;
            layout_height="fill";
            layout_width="fill";
            orientation="vertical";
            {
              LinearLayout;
              layout_height="20sp";
              layout_width="fill";
              gravity="center";
              {
                TextView;
                text="0d 0h 0m 0s";
                textSize="19sp";
                textColor="0xFFCDCDCD";
                id="txtExpire";
              };
            };
            {
              CheckBox;
              text="RED";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="colorRed";
            };
            {
              CheckBox;
              text="GREEN";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="colorGreen";
            };
            {
              CheckBox;
              text="GREY";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="colorGrey";
            };
            {
              CheckBox;
              text="COLORFUL";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="animColor";
            };
            {
              CheckBox;
              text="SMOOTHING";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="fps";
            };
            {
              CheckBox;
              text="SMOOTHING ULTRA";
              textSize="15sp";
              textColor="0xFFCDCDCD";
              id="fps0";
            };

          };
        };
      };
    };
  };


};